---
name: "pre-release"

#  Settings -> Actions -> General and give "Read and write permissions" to the Github Actions workflows.

on:
  push:
    tags:
      - "v1*"
      - "v2*"
      - "v3*"
  workflow_dispatch:
  
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    env:
        version: "1.0.0"

    steps:
      - uses: actions/checkout@v3
        with:
          path: "repository"
      - name: "Build & test"
        run: |
          java --version
          sudo apt update
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1347.sh
          chmod +x linux-install-1.11.1.1347.sh
          sudo ./linux-install-1.11.1.1347.sh
          sudo apt install openjdk-17-jdk-headless
          sudo apt install openjdk-17-jre-headless
          sudo apt install tree
          curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin
          clojure --version
          java --version
          lein --version
          pwd
          ls -l
          cd repository
          ls -l
          lein uberjar
          echo "done!"
          echo $version
          export version="2.0.0"
          echo $version

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.0.0"
          prerelease: false
          title: "$version"
          files: |
            repository/target/uberjar/*-standalone.jar
